# Generated by Django 3.1.7 on 2021-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='files/music/')),
                ('poster', models.ImageField(upload_to='files/music_poster/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('music', models.ManyToManyField(to='mainapp.MusicModel')),
            ],
        ),
    ]
