# Generated by Django 3.1.2 on 2021-03-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210321_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='status',
            field=models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM')], default='SILVER', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musicmodel',
            name='status',
            field=models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM')], default='SILVER', max_length=20, null=True),
        ),
    ]
