# Generated by Django 3.1.2 on 2021-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210322_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
