# Generated by Django 3.1.2 on 2021-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_albummodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='draft',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
