# Generated by Django 3.1.2 on 2021-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusermodel',
            name='face',
            field=models.ImageField(null=True, upload_to='user_faces/'),
        ),
    ]
